// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PeladaControladaAPI.Data;

#nullable disable

namespace PeladaControladaAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260104233926_AddUsuario")]
    partial class AddUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PeladaControladaAPI.Model.UsuarioCodigoOtp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Usado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuarioCodigosOtp");
                });

            modelBuilder.Entity("PeladaControladaAPI.model.Campeonato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_campeonato");

                    b.Property<bool>("CriadoAuto")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("criado_auto");

                    b.Property<DateTime?>("DataCriado")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_criado");

                    b.Property<DateOnly?>("DataFim")
                        .HasColumnType("date")
                        .HasColumnName("data_fim");

                    b.Property<DateOnly?>("DataInicio")
                        .HasColumnType("date")
                        .HasColumnName("data_inicio");

                    b.Property<DateTime?>("DataSalvo")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_salvo");

                    b.Property<bool>("DisputaEmDupla")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("disputa_em_dupla");

                    b.Property<bool>("DisputaTerceiroLugar")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("disputa_terceiro_lugar");

                    b.Property<int>("IdFase")
                        .HasColumnType("int")
                        .HasColumnName("id_fase");

                    b.Property<int>("IdTipo")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<bool>("IdaEVolta")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ida_e_volta");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext")
                        .HasColumnName("nome");

                    b.Property<bool>("PartidaFinal")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("partida_final");

                    b.Property<bool>("Salvo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("salvo");

                    b.Property<string>("Trofeu")
                        .HasColumnType("longtext")
                        .HasColumnName("trofeu");

                    b.HasKey("Id");

                    b.HasIndex("IdFase");

                    b.HasIndex("IdTipo");

                    b.HasIndex("IdUsuario");

                    b.ToTable("scc_campeonatos");
                });

            modelBuilder.Entity("PeladaControladaAPI.model.CategoriaEquipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_categoria");

                    b.Property<int>("IdTipo")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext")
                        .HasColumnName("nome");

                    b.Property<string>("Pasta")
                        .HasColumnType("longtext")
                        .HasColumnName("pasta");

                    b.HasKey("Id");

                    b.HasIndex("IdTipo");

                    b.ToTable("scc_categs_equipe");
                });

            modelBuilder.Entity("PeladaControladaAPI.model.Classificacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_classificacao");

                    b.Property<int>("Derrotas")
                        .HasColumnType("int")
                        .HasColumnName("derrotas");

                    b.Property<int>("Empates")
                        .HasColumnType("int")
                        .HasColumnName("empates");

                    b.Property<int>("GolsContra")
                        .HasColumnType("int")
                        .HasColumnName("golscontra");

                    b.Property<int>("GolsPro")
                        .HasColumnType("int")
                        .HasColumnName("golspro");

                    b.Property<int>("GrupoNumero")
                        .HasColumnType("int")
                        .HasColumnName("grupo");

                    b.Property<int>("IdCampeonato")
                        .HasColumnType("int")
                        .HasColumnName("id_campeonato");

                    b.Property<int>("IdTime")
                        .HasColumnType("int")
                        .HasColumnName("id_time");

                    b.Property<int>("Jogos")
                        .HasColumnType("int")
                        .HasColumnName("jogos");

                    b.Property<int>("Pontos")
                        .HasColumnType("int")
                        .HasColumnName("pontos");

                    b.Property<int>("SaldoGols")
                        .HasColumnType("int")
                        .HasColumnName("salgogols");

                    b.Property<int>("Vitorias")
                        .HasColumnType("int")
                        .HasColumnName("vitorias");

                    b.HasKey("Id");

                    b.HasIndex("IdCampeonato");

                    b.HasIndex("IdTime");

                    b.ToTable("scc_classificacao");
                });

            modelBuilder.Entity("PeladaControladaAPI.model.Equipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_equipe");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ativo");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int")
                        .HasColumnName("id_categoria");

                    b.Property<string>("Logo")
                        .HasColumnType("longtext")
                        .HasColumnName("logo");

                    b.Property<int>("Nivel")
                        .HasColumnType("int")
                        .HasColumnName("nivel");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext")
                        .HasColumnName("nome");

                    b.Property<string>("Sigla")
                        .HasColumnType("longtext")
                        .HasColumnName("sigla");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoria");

                    b.ToTable("scc_equipes");
                });

            modelBuilder.Entity("PeladaControladaAPI.model.Fase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_fase");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext")
                        .HasColumnName("descricao");

                    b.HasKey("Id");

                    b.ToTable("scc_fases");
                });

            modelBuilder.Entity("PeladaControladaAPI.model.Grupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_grupo");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_criacao");

                    b.Property<int>("IdCampeonato")
                        .HasColumnType("int")
                        .HasColumnName("id_campeonato");

                    b.Property<int?>("IdJogador1")
                        .HasColumnType("int")
                        .HasColumnName("id_jogador1");

                    b.Property<int?>("IdJogador2")
                        .HasColumnType("int")
                        .HasColumnName("id_jogador2");

                    b.Property<int>("NivelJogador1")
                        .HasColumnType("int")
                        .HasColumnName("nivel_jogador1");

                    b.Property<int>("NivelJogador2")
                        .HasColumnType("int")
                        .HasColumnName("nivel_jogador2");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("IdCampeonato");

                    b.HasIndex("IdJogador1");

                    b.HasIndex("IdJogador2");

                    b.ToTable("scc_grupos");
                });

            modelBuilder.Entity("PeladaControladaAPI.model.Jogador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_jogador");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("longblob")
                        .HasColumnName("foto");

                    b.Property<int?>("IdUsuarioDono")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario_dono");

                    b.Property<int?>("IdUsuarioRel")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario_rel");

                    b.Property<double>("MediaGolsMax")
                        .HasColumnType("double")
                        .HasColumnName("mediagols_max");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext")
                        .HasColumnName("nome");

                    b.Property<int>("PontuacaoAnterior")
                        .HasColumnType("int")
                        .HasColumnName("pontuacao_anterior");

                    b.Property<int>("PontuacaoAtual")
                        .HasColumnType("int")
                        .HasColumnName("pontuacao_atual");

                    b.Property<int>("PosicaoRankingAnterior")
                        .HasColumnType("int")
                        .HasColumnName("posicao_ranking_anterior");

                    b.Property<int>("PosicaoRankingAtual")
                        .HasColumnType("int")
                        .HasColumnName("posicao_ranking_atual");

                    b.Property<int>("QtdArtilharias")
                        .HasColumnType("int")
                        .HasColumnName("qtd_artilharias");

                    b.Property<int>("QtdArtilheiroConsecAtual")
                        .HasColumnType("int")
                        .HasColumnName("qtd_artilheiro_consec_atual");

                    b.Property<int>("QtdArtilheiroConsecMax")
                        .HasColumnType("int")
                        .HasColumnName("qtd_artilheiro_consec_max");

                    b.Property<int>("QtdCampeaoConsecAtual")
                        .HasColumnType("int")
                        .HasColumnName("qtd_campeao_consec_atual");

                    b.Property<int>("QtdCampeaoConsecMax")
                        .HasColumnType("int")
                        .HasColumnName("qtd_campeao_consec_max");

                    b.Property<int>("QtdCampeonatos")
                        .HasColumnType("int")
                        .HasColumnName("qtd_campeonatos");

                    b.Property<int>("QtdDefesas")
                        .HasColumnType("int")
                        .HasColumnName("qtd_defesas");

                    b.Property<int>("QtdDerrotas")
                        .HasColumnType("int")
                        .HasColumnName("qtd_derrotas");

                    b.Property<int>("QtdEmpates")
                        .HasColumnType("int")
                        .HasColumnName("qtd_empates");

                    b.Property<int>("QtdGols")
                        .HasColumnType("int")
                        .HasColumnName("qtd_gols");

                    b.Property<int>("QtdLanternas")
                        .HasColumnType("int")
                        .HasColumnName("qtd_lanternas");

                    b.Property<int>("QtdMelhorDefesaConsecAtual")
                        .HasColumnType("int")
                        .HasColumnName("qtd_melhordefesa_consec_atual");

                    b.Property<int>("QtdMelhorDefesaConsecMax")
                        .HasColumnType("int")
                        .HasColumnName("qtd_melhordefesa_consec_max");

                    b.Property<int>("QtdPartidas")
                        .HasColumnType("int")
                        .HasColumnName("qtd_partidas");

                    b.Property<int>("QtdTitulos")
                        .HasColumnType("int")
                        .HasColumnName("qtd_titulos");

                    b.Property<int>("QtdVitorias")
                        .HasColumnType("int")
                        .HasColumnName("qtd_vitorias");

                    b.Property<int>("QtdVitoriasConsecAtual")
                        .HasColumnType("int")
                        .HasColumnName("qtd_vitorias_consec_atual");

                    b.Property<int>("QtdVitoriasConsecMax")
                        .HasColumnType("int")
                        .HasColumnName("qtd_vitorias_consec_max");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuarioDono");

                    b.ToTable("scc_jogadores");
                });

            modelBuilder.Entity("PeladaControladaAPI.model.Jogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_jogo");

                    b.Property<bool>("CriadoAuto")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("criado_auto");

                    b.Property<DateTime?>("DataCriado")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_criado");

                    b.Property<DateTime?>("DataSalvo")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_salvo");

                    b.Property<int>("GolTime1")
                        .HasColumnType("int")
                        .HasColumnName("gol_time1");

                    b.Property<int>("GolTime2")
                        .HasColumnType("int")
                        .HasColumnName("gol_time2");

                    b.Property<int>("Grupo")
                        .HasColumnType("int")
                        .HasColumnName("grupo");

                    b.Property<int>("IdCampeonato")
                        .HasColumnType("int")
                        .HasColumnName("id_campeonato");

                    b.Property<int>("IdFase")
                        .HasColumnType("int")
                        .HasColumnName("id_fase");

                    b.Property<int>("IdTime1")
                        .HasColumnType("int")
                        .HasColumnName("id_time1");

                    b.Property<int>("IdTime2")
                        .HasColumnType("int")
                        .HasColumnName("id_time2");

                    b.Property<int>("Numero")
                        .HasColumnType("int")
                        .HasColumnName("numero");

                    b.Property<bool>("PartidaFinal")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("partida_final");

                    b.Property<int>("Penalti")
                        .HasColumnType("int")
                        .HasColumnName("penalti");

                    b.Property<int>("Rodada")
                        .HasColumnType("int")
                        .HasColumnName("rodada");

                    b.Property<bool>("Salvo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("salvo");

                    b.HasKey("Id");

                    b.HasIndex("IdCampeonato");

                    b.HasIndex("IdFase");

                    b.HasIndex("IdTime1");

                    b.HasIndex("IdTime2");

                    b.ToTable("scc_jogos");
                });

            modelBuilder.Entity("PeladaControladaAPI.model.Pontuacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_pontuacao");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data");

                    b.Property<int>("IdCampeonato")
                        .HasColumnType("int")
                        .HasColumnName("id_campeonato");

                    b.Property<int>("IdJogador")
                        .HasColumnType("int")
                        .HasColumnName("id_jogador");

                    b.Property<int>("Pontos")
                        .HasColumnType("int")
                        .HasColumnName("pontos");

                    b.HasKey("Id");

                    b.HasIndex("IdCampeonato");

                    b.HasIndex("IdJogador");

                    b.ToTable("scc_pontuacoes");
                });

            modelBuilder.Entity("PeladaControladaAPI.model.Time", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_time");

                    b.Property<int>("Derrotas")
                        .HasColumnType("int")
                        .HasColumnName("derrotas");

                    b.Property<int>("Empates")
                        .HasColumnType("int")
                        .HasColumnName("empates");

                    b.Property<int>("GolsContra")
                        .HasColumnType("int")
                        .HasColumnName("golscontra");

                    b.Property<int>("GolsPro")
                        .HasColumnType("int")
                        .HasColumnName("golspro");

                    b.Property<int>("IdCampeonato")
                        .HasColumnType("int")
                        .HasColumnName("id_campeonato");

                    b.Property<int>("IdEquipe")
                        .HasColumnType("int")
                        .HasColumnName("id_equipe");

                    b.Property<int?>("IdGrupo")
                        .HasColumnType("int")
                        .HasColumnName("id_grupo");

                    b.Property<double>("MediaGols")
                        .HasColumnType("double")
                        .HasColumnName("media_gols");

                    b.Property<bool>("MelhorAtaque")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("melhor_ataque");

                    b.Property<bool>("MelhorDefesa")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("melhor_defesa");

                    b.Property<int>("Nivel")
                        .HasColumnType("int")
                        .HasColumnName("nivel");

                    b.Property<int>("PosicaoFinal")
                        .HasColumnType("int")
                        .HasColumnName("posicao_final");

                    b.Property<int>("QtdJogos")
                        .HasColumnType("int")
                        .HasColumnName("qtd_jogos");

                    b.Property<int>("Vitorias")
                        .HasColumnType("int")
                        .HasColumnName("vitorias");

                    b.HasKey("Id");

                    b.HasIndex("IdCampeonato");

                    b.HasIndex("IdEquipe");

                    b.HasIndex("IdGrupo");

                    b.ToTable("scc_times");
                });

            modelBuilder.Entity("PeladaControladaAPI.model.TipoCampeonato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tipo");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("scc_tipos_campeonato");
                });

            modelBuilder.Entity("PeladaControladaAPI.model.TipoEquipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tipo");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("scc_tipos_equipe");
                });

            modelBuilder.Entity("PeladaControladaAPI.model.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<DateOnly?>("DataCadastro")
                        .HasColumnType("date")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("NomeUsuario")
                        .HasColumnType("longtext")
                        .HasColumnName("usuario");

                    b.Property<string>("Senha")
                        .HasColumnType("longtext")
                        .HasColumnName("senha");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext")
                        .HasColumnName("telefone");

                    b.HasKey("Id");

                    b.ToTable("scc_usuarios");
                });

            modelBuilder.Entity("PeladaControladaAPI.Model.UsuarioCodigoOtp", b =>
                {
                    b.HasOne("PeladaControladaAPI.model.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PeladaControladaAPI.model.Campeonato", b =>
                {
                    b.HasOne("PeladaControladaAPI.model.Fase", "Fase")
                        .WithMany()
                        .HasForeignKey("IdFase")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PeladaControladaAPI.model.TipoCampeonato", "Tipo")
                        .WithMany()
                        .HasForeignKey("IdTipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PeladaControladaAPI.model.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fase");

                    b.Navigation("Tipo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PeladaControladaAPI.model.CategoriaEquipe", b =>
                {
                    b.HasOne("PeladaControladaAPI.model.TipoEquipe", "TipoEquipe")
                        .WithMany()
                        .HasForeignKey("IdTipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoEquipe");
                });

            modelBuilder.Entity("PeladaControladaAPI.model.Classificacao", b =>
                {
                    b.HasOne("PeladaControladaAPI.model.Campeonato", "Campeonato")
                        .WithMany()
                        .HasForeignKey("IdCampeonato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PeladaControladaAPI.model.Time", "Time")
                        .WithMany()
                        .HasForeignKey("IdTime")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campeonato");

                    b.Navigation("Time");
                });

            modelBuilder.Entity("PeladaControladaAPI.model.Equipe", b =>
                {
                    b.HasOne("PeladaControladaAPI.model.CategoriaEquipe", "Categoria")
                        .WithMany()
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("PeladaControladaAPI.model.Grupo", b =>
                {
                    b.HasOne("PeladaControladaAPI.model.Campeonato", "Campeonato")
                        .WithMany()
                        .HasForeignKey("IdCampeonato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PeladaControladaAPI.model.Jogador", "Jogador1")
                        .WithMany()
                        .HasForeignKey("IdJogador1")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PeladaControladaAPI.model.Jogador", "Jogador2")
                        .WithMany()
                        .HasForeignKey("IdJogador2")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Campeonato");

                    b.Navigation("Jogador1");

                    b.Navigation("Jogador2");
                });

            modelBuilder.Entity("PeladaControladaAPI.model.Jogador", b =>
                {
                    b.HasOne("PeladaControladaAPI.model.Usuario", "UsuarioDono")
                        .WithMany()
                        .HasForeignKey("IdUsuarioDono");

                    b.Navigation("UsuarioDono");
                });

            modelBuilder.Entity("PeladaControladaAPI.model.Jogo", b =>
                {
                    b.HasOne("PeladaControladaAPI.model.Campeonato", "Campeonato")
                        .WithMany()
                        .HasForeignKey("IdCampeonato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PeladaControladaAPI.model.Fase", "Fase")
                        .WithMany()
                        .HasForeignKey("IdFase")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PeladaControladaAPI.model.Time", "Time1")
                        .WithMany()
                        .HasForeignKey("IdTime1")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PeladaControladaAPI.model.Time", "Time2")
                        .WithMany()
                        .HasForeignKey("IdTime2")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campeonato");

                    b.Navigation("Fase");

                    b.Navigation("Time1");

                    b.Navigation("Time2");
                });

            modelBuilder.Entity("PeladaControladaAPI.model.Pontuacao", b =>
                {
                    b.HasOne("PeladaControladaAPI.model.Campeonato", "Campeonato")
                        .WithMany()
                        .HasForeignKey("IdCampeonato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PeladaControladaAPI.model.Jogador", "Jogador")
                        .WithMany()
                        .HasForeignKey("IdJogador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campeonato");

                    b.Navigation("Jogador");
                });

            modelBuilder.Entity("PeladaControladaAPI.model.Time", b =>
                {
                    b.HasOne("PeladaControladaAPI.model.Campeonato", "Campeonato")
                        .WithMany()
                        .HasForeignKey("IdCampeonato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PeladaControladaAPI.model.Equipe", "Equipe")
                        .WithMany()
                        .HasForeignKey("IdEquipe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PeladaControladaAPI.model.Grupo", "Grupo")
                        .WithMany()
                        .HasForeignKey("IdGrupo");

                    b.Navigation("Campeonato");

                    b.Navigation("Equipe");

                    b.Navigation("Grupo");
                });
#pragma warning restore 612, 618
        }
    }
}
